-- Required table for audit records

CREATE TABLE AuditLog (
LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
TransactionID NUMBER,
LogDate DATE,
Action VARCHAR2(100)
);
/

CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN

```
-- Update last modified date
:NEW.LastModified := SYSDATE;
```

END;
/

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN

```
-- Insert transaction details into audit log
INSERT INTO AuditLog(
    TransactionID,
    LogDate,
    Action
)
VALUES(
    :NEW.TransactionID,
    SYSDATE,
    'Transaction Added'
);
```

END;
/

CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
v_bal NUMBER;
BEGIN

```
-- Deposit amount must be positive
IF :NEW.TransactionType = 'Deposit'
   AND :NEW.Amount <= 0 THEN

   RAISE_APPLICATION_ERROR(
       -20001,
       'Deposit amount must be positive'
   );

END IF;

-- Check withdrawal balance
IF :NEW.TransactionType = 'Withdrawal' THEN

    SELECT Balance
    INTO v_bal
    FROM Accounts
    WHERE AccountID = :NEW.AccountID;

    IF :NEW.Amount > v_bal THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'Insufficient Balance'
        );
    END IF;

END IF;
```

END;
/

-- Test Trigger 1
UPDATE Customers
SET Balance = 2000
WHERE CustomerID = 1;
/

-- Test Trigger 2
INSERT INTO Transactions(
TransactionID,
AccountID,
TransactionDate,
Amount,
TransactionType
)
VALUES(
10,
1,
SYSDATE,
500,
'Deposit'
);
/

-- Test Trigger 3
INSERT INTO Transactions(
TransactionID,
AccountID,
TransactionDate,
Amount,
TransactionType
)
VALUES(
11,
1,
SYSDATE,
200,
'Withdrawal'
);
/
